# Generated by Django 4.2.3 on 2023-08-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
