# Generated by Django 4.2.4 on 2023-09-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_mailing_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
