# Generated by Django 4.2.4 on 2023-09-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_alter_client_owner_alter_mailing_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='owner',
            new_name='client_owner',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='owner',
            new_name='mailing_owner',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='message_owner',
        ),
    ]
