# Generated by Django 4.2.4 on 2023-09-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_rename_client_owner_client_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_manager_view', 'Разрешение для менеджера на просмотр рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
