# Generated by Django 4.2.4 on 2023-09-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_alter_mailing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, null=True, verbose_name='сообщение'),
        ),
    ]
