# Generated by Django 4.2.4 on 2023-09-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_log_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='последняя отправка'),
        ),
    ]
