# Generated by Django 4.2.4 on 2023-09-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0013_mailing_last_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='сообщение'),
        ),
    ]
